### ISSUE TITLE
User Can See Their Car

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create a HTML form
- [x] create a CSS form
- [x] set the photo of the car on a green background
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
