### ISSUE TITLE
User Can Turn Their Car

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [ ] Apply CSS classes rotate to work with arrow keys
- [ ] Use JavaScript to change classes on the image when arrow keys are pressed
- [ ] Use addeventlisteners to change classes - keydown.
